package com.geriaTeam.geriatricare.entities.enums;

public enum CondicaoMentalEnums {
    DEPRESSAO,
    ANSIEDADE,
    TRANSTORNO_BIPOLAR,
    ESQUIZOFRENIA,
    DEMENCIA,
    ALZHEIMER,
    TRANSTORNO_OBSESSIVO_COMPULSIVO,
    TRANSTORNO_DE_ESTRESSE_POS_TRAUMATICO,
    TRANSTORNO_DE_PERSONALIDADE,
    OUTROS
}