package com.geriaTeam.geriatricare.entities.enums;

public enum TipoBeneficioEnums
    ACOMPANHAMENTO_MEDICO,
    ASSISTENCIA_DOMICILIAR,
    REFEICOES_BALANCEADAS,
    ATIVIDADES_RECREATIVAS,
    FISIOTERAPIA,
    TERAPIA_OCUPACIONAL,
    TRANSPORTE_ADAPTADO,
    SUPORTE_PSICOLOGICO,
    MONITORAMENTO_24H,
    PROGRAMAS_SOCIAIS,
    DESCONTO_EM_MEDICAMENTOS,
    CONSULTAS_ESPECIALIZADAS
}
